[package]
name = "muse"
version = "0.0.1"
edition = "2021"

[dependencies]
nostr-sdk = "0.36"
tokio = {version = "1", features = ["full"]}
tracing-subscriber = "0.3"
dashmap = "6.1"
once_cell = "1.20"
